sudo: required
language: python
services:
  - redis-server
sudo: false
addons:
  apt:
    packages:
    - shellcheck
    - git
before_install:
  - pip install hererocks
  - hererocks -r^ --luajit=2.0 ${HOME}/usr
  - export PATH=${HOME}/usr/bin:${PATH}
  - luarocks install luacheck
  - luarocks install https://raw.githubusercontent.com/saucisson/lua-resty-busted/master/lua-resty-busted-master-0.rockspec
script:
  - shellcheck update.sh
  - luacheck src/
  - REDIS="localhost" resty_busted src/
notifications:
  email:
    - alban.linard@gmail.com
  on_success: change
  on_failure: change
