version: "3"
services:
  redis:
    image: redis:alpine
    logging:
      driver: none
  resty-redis-mapper:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - /tmp/sources/update.sh
    volumes:
      - .:/tmp/sources
